name: Build APK Android

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Créer le fichier .env
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

      - run: npm run build
      - run: npx cap sync android

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - run: chmod +x android/gradlew

      - name: Compiler l'APK (debug)
        working-directory: android
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: quetes-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
